name: BasicMinigameFormula
version: '${project.version}'
main: me.hiremedev.basicminigameformula.BasicMinigameFormula
api-version: 1.17

commands:
  start:
    usage: /start
    description: moves the game state to pregame
